server:
  port: 8081



#mybatis:
#  mapper-locations: classpath:Mapper/*.xml
#  type-aliases-package: com.lly.elgb.entity


#showSql
logging:
  level:
    com:
      lly:
        business:
          mapper: debug







### Redis 配置
#redis:
#    ## Redis数据库索引（默认为0）
#  database: 0
#    ## Redis服务器地址
#  host: 192.168.79.131
#    ## Redis服务器连接端口
#  port: 6379
#    ## Redis服务器连接密码（默认为空）
#  password:
#    jedis:
#      pool:
#        ## 连接池最大连接数（使用负值表示没有限制）
#        #spring.redis.pool.max-active=8
#        max-active: 8
#        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        #spring.redis.pool.max-wait=-1
#        max-wait: -1
#        ## 连接池中的最大空闲连接
#        #spring.redis.pool.max-idle=8
#        max-idle: 8
#        ## 连接池中的最小空闲连接
#        #spring.redis.pool.min-idle=0
#        min-idle: 0
#    ## 连接超时时间（毫秒）
#    timeout: 1200